language: node_js
node_js:
- 16.16.0
install:
- npm ci
script:
- npm run test

branches:
  only:
  - main
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  skip-cleanup: true
  api_key: $HEROKU_API_KEY
  app:
    main: c10-app-staging

